# Generated by Django 4.2.23 on 2025-09-03 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0003_alter_team_league'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='height_cm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(choices=[('GK', 'Goalkeeper'), ('DF', 'Defender'), ('MF', 'Midfielder'), ('FW', 'Forward')], max_length=50, null=True),
        ),
    ]
