# Generated by Django 4.2.16 on 2025-03-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0003_alter_team_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='team_logos/'),
        ),
    ]
