# Generated by Django 4.2.23 on 2025-09-04 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0004_player_height_cm_alter_player_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='league',
        ),
        migrations.AddField(
            model_name='team',
            name='league',
            field=models.ManyToManyField(blank=True, related_name='teams', to='pitch.league'),
        ),
    ]
