# Generated by Django 4.2.23 on 2025-10-20 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0005_remove_team_league_team_league'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished')], default='scheduled', max_length=20),
        ),
    ]
