# Generated by Django 4.2.23 on 2025-10-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pitch', '0006_alter_match_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('finished', 'Finished'), ('postponed', 'Postponed')], default='scheduled', editable=False, max_length=20),
        ),
    ]
